# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', models.ImageField(upload_to=b'', verbose_name='Logo')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('condition', models.CharField(choices=[(b'NEW', b'New'), (b'USED', b'Used')], max_length=100)),
                ('category', models.CharField(choices=[(b'CAR', b'Car'), (b'MOTORCYCLE', b'MotorCycle'), (b'VEHICLE', b'Vehicle')], default=b'', max_length=50, verbose_name='category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('details', models.TextField(blank=True, help_text='Enter car details', verbose_name='details')),
                ('location', models.CharField(default=b'', max_length=100, verbose_name='locations')),
                ('transmission', models.CharField(choices=[(b'AUTOMATIC', b'Automatic'), (b'MANUAL', b'Manual')], default=b'', max_length=100, verbose_name='transmission')),
                ('fuel', models.CharField(choices=[(b'DIESEL', b'Diesel'), (b'ELECTRO', b'Electro'), (b'GASOLINE', b'Gasoline')], default=b'', max_length=100)),
                ('lifestyle', models.CharField(choices=[(b'FAMILY', b'Family'), (b'LUXURY', b'Luxury'), (b'OFFROAD', b'Offroad')], max_length=100, null=True)),
                ('seller_type', models.CharField(choices=[(b'DEALER', b'Dealer'), (b'PRIVATE', b'Private')], default=b'', max_length=100)),
                ('mileage', models.CharField(default=b'', max_length=100)),
                ('color_family', models.CharField(default=b'', max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='Car.Brand', verbose_name='brand')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Spec',
                'verbose_name_plural': 'Specs',
            },
        ),
    ]
