# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spec',
            options={'verbose_name': 'Spec', 'verbose_name_plural': 'Specs'},
        ),
        migrations.RemoveField(
            model_name='spec',
            name='id',
        ),
        migrations.AlterField(
            model_name='spec',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='name'),
        ),
    ]
