# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_auto_20170118_1253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Specs',
        ),
    ]
