# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='details',
            field=models.TextField(blank=True, verbose_name='details'),
        ),
    ]
