# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_auto_20170118_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specs',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='specs',
            name='conditions',
        ),
        migrations.DeleteModel(
            name='Specs',
        ),
    ]
