# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_auto_20170119_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('CAR', 'Car'), ('MOTORCYCLE', 'MotorCycle'), ('VEHICLE', 'Vehicle')], max_length=50)),
                ('date_submitted', models.DateField()),
                ('price', models.IntegerField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='spec',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.Brand'),
        ),
        migrations.AddField(
            model_name='spec',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.Condition'),
        ),
    ]
