# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_auto_20170119_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='old',
            new_name='used',
        ),
    ]
