# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0006_auto_20170120_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='slug',
            field=models.SlugField(default='DEFAULT VALUE', unique=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
