# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0007_auto_20170120_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
