# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0008_auto_20170121_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='used',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='spec',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='Car.Condition'),
        ),
    ]
