# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0012_auto_20170121_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
