# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0013_auto_20170121_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='types',
        ),
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='build',
            field=models.DateField(default=b''),
        ),
        migrations.AddField(
            model_name='spec',
            name='category',
            field=models.CharField(choices=[(b'CAR', b'Car'), (b'MOTORCYCLE', b'MotorCycle'), (b'VEHICLE', b'Vehicle')], default=b'', max_length=50, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='spec',
            name='color_family',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='spec',
            name='fuel',
            field=models.CharField(choices=[(b'DIESEL', b'Diesel'), (b'ELECTRO', b'Electro'), (b'GASOLINE', b'Gasoline')], default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='spec',
            name='lifestyle',
            field=models.CharField(choices=[(b'FAMILY', b'Family'), (b'LUXURY', b'Luxury'), (b'OFFROAD', b'Offroad')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spec',
            name='location',
            field=models.CharField(default=b'', max_length=100, verbose_name='locations'),
        ),
        migrations.AddField(
            model_name='spec',
            name='mileage',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='spec',
            name='seller_type',
            field=models.CharField(choices=[(b'DEALER', b'Dealer'), (b'PRIVATE', b'Private')], default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='spec',
            name='transmission',
            field=models.CharField(choices=[(b'AUTOMATIC', b'Automatic'), (b'MANUAL', b'Manual')], default=b'', max_length=100, verbose_name='transmission'),
        ),
        migrations.AlterField(
            model_name='spec',
            name='condition',
            field=models.CharField(choices=[(b'NEW', b'New'), (b'USED', b'Used')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
