# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0014_auto_20170125_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='build',
            field=models.DateTimeField(default=b''),
        ),
    ]
