# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0020_auto_20170125_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='build',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Build'),
        ),
    ]
