# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0024_auto_20170125_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='date_submitted',
        ),
        migrations.AlterField(
            model_name='spec',
            name='build',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date submitted'),
        ),
    ]
