# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0025_auto_20170125_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spec',
            old_name='build',
            new_name='date_submitted',
        ),
    ]
