# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0028_auto_20170125_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='date_submitted',
        ),
    ]
