# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PHILIPPINES', 'Philippines'), ('JAPAN', 'Japan'), ('CHINA', 'China')], max_length=20)),
            ],
        ),
    ]
